### ISSUE TITLE
transitive dependency error while working with cocoapods

### ISSUE THREAD

**Issue by phanisai4u** [hohl/MIHCrypto#51] opened 2017-02-24 05:58 UTC
The 'Pods' target has transitive dependencies that include static binaries: (/Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libcrypto.a and /Users/xxx/workspace/xcode/iBBS-Swift/Pods/OpenSSL/lib/libssl.a)in

**Comment by hohl** [comment] 2017-02-24 15:36
duplicate of #40

**Closed by hohl** 2017-02-24 15:36 UTC
